name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: pycodestyle
      uses: conda-incubator/setup-miniconda@v2
      with: 
        environment-file: environment.yaml
        environment-name: swe4s
    - name: run the style check 
      run: pycodestyle $(git ls-files "*.py") 
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: swe4s
    - name: run the unit test 
      run: |
        cd test/unit
        python -m unittest test_utils
