name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with: 
          activate-enviornment: swe4s
          environment-file: environment.yaml
      - run: |
          cd test/func
          bash test_search.sh
    
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: pycodestyle
      uses: conda-incubator/setup-miniconda@v2
      with: 
        activate-enviornment: swe4s
        environment-file: environment.yaml
    - name: run the style check 
      run: pycodestyle $(git ls-files "*.py") 
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        activate-enviornment: swe4s
        environment-file: environment.yaml
    - name: run the unit test 
      run: |
        cd test/unit
        python -m unittest test_utils
