name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_style_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: swe4s
    - run: |
        pycodestyle $(git ls-files '*.py')
#  build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.8", "3.9", "3.10"]
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pylint
#     - name: Analysing the code with pylint
#       run: |
#         pylint $(git ls-files '*.py')
#  run_unit_test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install Conda environment with Micromamba
#       uses: mamba-org/provision-with-micromamba@main
#       with:
#         environment-file: environment.yaml
#         environment-name: swe4s
#     - name: run the unit test 
#       run: |
#         cd test/unit
#         python -m unittest test_utils
